# Generated by Django 5.2.7 on 2025-12-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Введите заголовок поста.",
                        max_length=100,
                        verbose_name="Заголовок",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Введите содержимое поста.",
                        verbose_name="Содержимое поста",
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        help_text="Добавьте изображение для поста.",
                        null=True,
                        upload_to="catalog/preview",
                        verbose_name="Изображение поста",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        blank=True,
                        help_text="Добавьте дату создания поста.",
                        null=True,
                        verbose_name="Дата создания поста",
                    ),
                ),
                (
                    "published_is",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="Отметьте, если пост опубликован",
                        verbose_name="Опубликовано",
                    ),
                ),
                (
                    "view_counter",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Укажите количество просмотров поста.",
                        verbose_name="Счетчик просмотров поста",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
                "ordering": ["title", "created_at", "published_is", "view_counter"],
            },
        ),
    ]
