# Generated by Django 5.2.7 on 2025-12-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="preview",
            field=models.ImageField(
                blank=True,
                help_text="Добавьте изображение для поста.",
                null=True,
                upload_to="blog/preview",
                verbose_name="Изображение поста",
            ),
        ),
    ]
