# Generated by Django 5.2.7 on 2025-12-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_product_view_counter_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="delivery_option_is",
            field=models.BooleanField(
                default=False,
                help_text="Отметьте галочкой, если есть возможность доставки товара.",
                verbose_name="Возможность доставки товара на дом.",
            ),
        ),
    ]
