# Generated by Django 5.2.7 on 2025-12-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_product_delivery_option_is"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="delivery_option_is",
            field=models.BooleanField(
                default=False,
                help_text="Отметьте галочкой, если есть возможность доставки товара.",
                verbose_name="Возможность доставки",
            ),
        ),
    ]
