# Generated by Django 4.2.2 on 2026-01-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_product_delivery_option_is"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name", "category", "price", "created_at", "updated_at"],
                "permissions": [
                    ("can_unpublish_product", "Can unpublish product"),
                    ("can_delete_product", "Can delete product"),
                ],
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="published_is",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Отметьте, если нужно опубликовать",
                verbose_name="Опубликовано",
            ),
        ),
    ]
